# Generated by Django 5.2.6 on 2025-09-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rf', models.CharField(max_length=50, unique=True)),
                ('satisfaccion', models.IntegerField()),
                ('necesidad', models.IntegerField()),
                ('tecnica', models.IntegerField()),
                ('dependencia', models.IntegerField()),
                ('resultado', models.FloatField()),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
    ]
