# Generated by Django 5.2.6 on 2025-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
