# Generated by Django 5.2.6 on 2025-10-09 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntd', '0002_categorias_requerimiento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sntd.categorias'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
    ]
