# Generated by Django 5.2.6 on 2025-10-09 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntd', '0003_requerimiento_categoria_requerimiento_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='sntd.categorias'),
        ),
    ]
